<?php

namespace TonerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MarcaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarcaRepository extends EntityRepository
{
}
